Repository zenml-io/mlstacks, pull requests merged in 2023-09, with the labels that each got.

#91 Add link to Github repository in TOC
  docs/book/toc.md
Labels: documentation, internal

#90 Add CodeQL checks
  .github/workflows/codeql.yml
Labels: enhancement, tests, dependency, security

#94 Add missing Vertex flavor
  src/mlstacks/enums.py
Labels: bug, internal

#93 Fix "Permission Denied" error while executing dig script
  src/mlstacks/terraform/modules/nginx-ingress-module/output.tf
Labels: bug, internal

#95 Stop CI from running on push to `develop` branch
  .github/workflows/ci.yml
Labels: enhancement, internal

#97 Add remote state deployment + use by default
  .gitignore
  docs/book/getting-started/aws.md
  docs/book/getting-started/core-concepts.md
  docs/book/getting-started/gcp.md
  docs/book/reference/cli.md
  docs/book/reference/faq.md
  pyproject.toml
  src/mlstacks/cli/cli.py
  src/mlstacks/constants.py
  src/mlstacks/enums.py
  src/mlstacks/terraform/aws-modular/values.tfvars.json
  src/mlstacks/terraform/aws-remote-state/main.tf
  src/mlstacks/terraform/aws-remote-state/outputs.tf
  src/mlstacks/terraform/aws-remote-state/variables.tf
  src/mlstacks/terraform/gcp-modular/values.tfvars.json
  src/mlstacks/terraform/gcp-remote-state/main.tf
  src/mlstacks/terraform/gcp-remote-state/outputs.tf
  src/mlstacks/terraform/gcp-remote-state/values.tfvars.json
  src/mlstacks/terraform/gcp-remote-state/variables.tf
  src/mlstacks/terraform/remote-state-terraform-config/terraform-aws.tf
  src/mlstacks/terraform/remote-state-terraform-config/terraform-gcp.tf
  src/mlstacks/utils/terraform_utils.py
  tests/utils/test_terraform_utils.py
Labels: enhancement, internal

#101 Update PR template to discourage PRs on `main`
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: documentation, enhancement

#99 Add `skypilot` support for AWS and GCP
  docs/book/stacks/aws.md
  docs/book/stacks/gcp.md
  docs/book/stacks/k3d.md
  src/mlstacks/constants.py
  src/mlstacks/enums.py
  src/mlstacks/terraform/aws-modular/output_file.tf
  src/mlstacks/terraform/aws-modular/variables.tf
  src/mlstacks/terraform/gcp-modular/output_file.tf
  src/mlstacks/terraform/gcp-modular/variables.tf
Labels: documentation, enhancement, internal

#100 Close quotes on `kubernetes_context` values in `gcp-modular`
  src/mlstacks/terraform/gcp-modular/output_file.tf
Labels: bug
