Repository zenml-io/mlstacks, pull requests merged in 2023-08, with the labels that each got.

#70 Add starter docs
  docs/README.md
  docs/SUMMARY.md
  docs/fundamentals/contributing-deployments.md
  docs/fundamentals/how-it-works.md
  docs/overview/getting-started.md
  docs/product-guides/integrations.md
  docs/product-guides/spec-file.md
  docs/use-cases/for-data-scientists.md
  docs/use-cases/for-mlops-platform-engineers.md
Labels: documentation, internal

#71 Fixing broken links after the docs update
  aws-kubeflow-kserve/README.md
  aws-minimal/README.md
  aws-modular/README.md
  aws-stores-minimal/README.md
  azure-minimal/README.md
  azureml-minimal/README.md
  docs/README.md
  gcp-airflow/README.md
  gcp-kubeflow-kserve/README.md
  gcp-minimal/README.md
  gcp-modular/README.md
  gcp-vertexai/README.md
  k3d-modular/README.md
  src/mlstacks/terraform/aws-modular/README.md
  src/mlstacks/terraform/gcp-modular/README.md
  src/mlstacks/terraform/k3d-modular/README.md
Labels: documentation, internal

#72 Update links following rename
  docs/book/reference/terraform.md
  docs/book/stacks/aws.md
  docs/book/stacks/azure.md
  docs/book/stacks/gcp.md
  docs/book/stacks/k3d.md
  pyproject.toml
Labels: documentation, internal

#73 Add analytics to `mlstacks`
  aws-kubeflow-kserve/kserve.tf
  docs/book/reference/analytics.md
  docs/book/toc.md
  pyproject.toml
  src/mlstacks/analytics/__init__.py
  src/mlstacks/analytics/client.py
  src/mlstacks/cli/cli.py
  src/mlstacks/constants.py
  src/mlstacks/enums.py
  src/mlstacks/utils/analytics_utils.py
  src/mlstacks/utils/terraform_utils.py
  tests/utils/test_analytics_utils.py
Labels: enhancement, internal

#76 Add VERSION file
  .github/workflows/publish-pypi-package.yml
  src/mlstacks/VERSION
Labels: enhancement, internal

#79 Add Python requirement for package
  pyproject.toml
Labels: bug, internal, dependency

#81 Bump `pyyaml` for ZenML
  pyproject.toml
Labels: bug, internal, dependency

#82 Bump incompatible packages
  pyproject.toml
Labels: bug, internal, dependency

#84 Add `zenml` <-> `mlstacks` compatibility check to CI
  .github/workflows/release.yml
Labels: enhancement, internal, tests

#83 Add missing `aws` flavor
  src/mlstacks/enums.py
Labels: bug, internal

#85 Update variable name for release publication token
  scripts/publish.sh
Labels: internal

#87 Renaming the environment variable for analytics
  .gitignore
  docs/book/reference/analytics.md
  src/mlstacks/analytics/client.py
  src/mlstacks/constants.py
  src/mlstacks/utils/environment_utils.py
Labels: documentation, enhancement, internal

#89 Update zenml-mlstacks sample command
  docs/book/reference/zenml.md
Labels: documentation, internal

#88 Handle errors more gracefully
  src/mlstacks/utils/terraform_utils.py
Labels: bug, enhancement, internal

#86 Use real Segment analytics package instead of deprecated version
  pyproject.toml
Labels: internal, dependency
