Repository zenml-io/mlstacks, pull requests merged in 2024-02, with the labels that each got.

#141 Fix/analytics connection hang
  src/mlstacks/analytics/client.py
  tests/unit/analytics/__init__.py
  tests/unit/analytics/test_custom_on_error.py
Labels: bug

#142 Prepare release 0.8.1
  pyproject.toml
  src/mlstacks/VERSION
  src/mlstacks/terraform/aws-modular/variables.tf
  src/mlstacks/terraform/gcp-modular/variables.tf
  src/mlstacks/terraform/k3d-modular/variables.tf
Labels: internal

#143 Remove dashboard from release workflow
  .github/workflows/publish-pypi-package.yml
Labels: bug, internal

#144 Improve git branching instructions in `CONTRIBUTIONS.md`
  CONTRIBUTING.md
Labels: documentation
