Repository zenml-io/mlstacks, pull requests merged in 2024-01, with the labels that each got.

#129 Convert underscores to hyphens in AWS Quickstart docs
  docs/book/getting-started/aws.md
Labels: bug, documentation

#128 Add `jq` as named dependency in documentation
  docs/book/getting-started/installation.md
Labels: documentation, internal

#131 Use GitHub as trusted publisher for PyPI publication
  .github/workflows/publish-pypi-package.yml
  scripts/publish.sh
Labels: bug, internal
